name: Hello World

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: colbyfayock/egghead-demo-github-action-hello-world@v1.0.1
